log.home: /data/logs/task-scheduler
app.version: 1.0.0
loglevel: info
app.name: task-scheduler
server:
  port: 9222
  servlet:
    context-path: /${app.name}
  tomcat:
    threads:
      max: 200 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.
aace:
  center:
    uri: aace://aace.xxx.net:16999/center

mybatis:
  mapper-locations: classpath*:/mybatis/*.xml
  config-location: classpath:mybatis-config.xml

spring:
  datasource.confKey: xxx_im
  application.name: ${app.name}
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"
    dispatch-trace-request: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    #https://www.cnblogs.com/woshimrf/p/LocalDate-serialize-json-springboot.html
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
  # REDIS (RedisProperties)
  redis:
    confKey: main
    database: 0 # Database index used by the connection factory.
  jedis.pool:
    max-total: 100 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
    max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
    min-idle: 4
    max-wait-millis: 5000 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet.enabled: false
      web-stat-filter.enabled: false
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      useGlobalDataSourceStat: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true